In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
url = 'https://www.bbc.com/korean/news-46562902'
r = requests.get(url)

soup = BeautifulSoup(r.text, "html.parser")

In [2]:
mr = soup.find(class_="story-body__introduction")

In [3]:
text = mr.get_text()

In [4]:
split_text = list(text)

In [5]:
spacing = []
for i in range(len(split_text)):
    if split_text[i] == ' ':
        spacing.append(([split_text[i-1], split_text[i+1]]))

In [6]:
spacing

[['늘', '밤'],
 [',', '쌍'],
 ['리', '유'],
 ['가', '쏟'],
 ['서', '2'],
 ['의', '가'],
 ['장', '화'],
 ['한', '우'],
 ['가', '밤'],
 ['에', '펼'],
 ['질', '것'],
 ['로', '보']]

In [535]:
split1 = split_text

In [536]:
split1

['오',
 '늘',
 ' ',
 '밤',
 ',',
 ' ',
 '쌍',
 '둥',
 '이',
 '자',
 '리',
 ' ',
 '유',
 '성',
 '우',
 '가',
 ' ',
 '쏟',
 '아',
 '지',
 '면',
 '서',
 ' ',
 '2',
 '0',
 '1',
 '8',
 '년',
 '의',
 ' ',
 '가',
 '장',
 ' ',
 '화',
 '려',
 '한',
 ' ',
 '우',
 '주',
 '쇼',
 '가',
 ' ',
 '밤',
 '하',
 '늘',
 '에',
 ' ',
 '펼',
 '쳐',
 '질',
 ' ',
 '것',
 '으',
 '로',
 ' ',
 '보',
 '인',
 '다',
 '.']

In [537]:
df = pd.get_dummies(split1)

In [538]:
df.values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=uint8)

In [539]:
split_text = list(filter((' ').__ne__, split_text))

In [540]:
split_text

['오',
 '늘',
 '밤',
 ',',
 '쌍',
 '둥',
 '이',
 '자',
 '리',
 '유',
 '성',
 '우',
 '가',
 '쏟',
 '아',
 '지',
 '면',
 '서',
 '2',
 '0',
 '1',
 '8',
 '년',
 '의',
 '가',
 '장',
 '화',
 '려',
 '한',
 '우',
 '주',
 '쇼',
 '가',
 '밤',
 '하',
 '늘',
 '에',
 '펼',
 '쳐',
 '질',
 '것',
 '으',
 '로',
 '보',
 '인',
 '다',
 '.']

In [541]:
split2 = split_text

In [542]:
split2

['오',
 '늘',
 '밤',
 ',',
 '쌍',
 '둥',
 '이',
 '자',
 '리',
 '유',
 '성',
 '우',
 '가',
 '쏟',
 '아',
 '지',
 '면',
 '서',
 '2',
 '0',
 '1',
 '8',
 '년',
 '의',
 '가',
 '장',
 '화',
 '려',
 '한',
 '우',
 '주',
 '쇼',
 '가',
 '밤',
 '하',
 '늘',
 '에',
 '펼',
 '쳐',
 '질',
 '것',
 '으',
 '로',
 '보',
 '인',
 '다',
 '.']

In [543]:
df2 = pd.get_dummies(split2)

In [544]:
df2.values.shape

(47, 42)

In [545]:
spacing[0][0]

'늘'

In [546]:
spacing[0][1]

'밤'

In [547]:
y = np.ones([47, 2])

In [548]:
for k in range(len(spacing)):
    for l in range(len(split2)):
        if split2[l] == spacing[k][0]:
            if split2[l+1] == spacing[k][1]:
                print(l)
                y[l][0] = y[l][0]-1

1
3
8
12
17
23
25
28
32
36
39
42


In [549]:
y

array([[1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [550]:
y[::-1]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.]])